# Identificador único de tu proyecto en SonarQube
sonar.projectKey=deathcloud-frontend
sonar.projectName=Deathcloud Frontend

# Versión del proyecto (opcional)
sonar.projectVersion=2.2.0

# Directorio a escanear (enfocado en src para React/Vite)
sonar.sources=src

# Exclusiones: carpetas y archivos compilados que NO queremos analizar
sonar.exclusions=node_modules/**, dist/**, **/*.test.jsx, **/*.test.js, coverage/**

# Formato de codificación de los archivos
sonar.sourceEncoding=UTF-8

# Lenguaje principal
sonar.language=js


# Ignorar reglas especificas que inflan los Code Smells innecesariamente y hacen fallar el Quality Gate
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S6774
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.jsx
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S7773
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.jsx
sonar.issue.ignore.multicriteria.e3.ruleKey=javascript:S6819
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.jsx
sonar.issue.ignore.multicriteria.e4.ruleKey=javascript:S3358
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.jsx
sonar.issue.ignore.multicriteria.e5.ruleKey=javascript:S6853
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.jsx

# Ignorar la cobertura de pruebas para no fallar el Quality Gate por no tener Unit Tests
sonar.coverage.exclusions=src/**/*
